<div> 
    <a href="http://code.google.com/p/gonium"> 
        <img src="/gonium/images/gonium_button_120x60-shadow-project.png" title="Gonium Project" alt="Gonium Project" width="120" height="60" /> 
    </a> 
</div>
<div>	
	<a href="http://labs.gon.cl/gonium/wblog/"> 
		<img src="/gonium/images/gonium_button_120x60-shadow-blog.png" title="Gonium Blog" alt="Gonium Blog" width="120" height="60" /> 
	</a> 
</div>
<div> 
    <a href="http://twitter.com/GoniumProject"> 
       <img src="/gonium/images/gonium_button_120x60-shadow-twitter.png" title="Gonium Twitter" alt="Gonium Twitter" width="120" height="60" /> 
    </a> 
</div>
<div>
    <a href="http://framework.zend.com/">
       <img title="Zend Framework" src="<?php echo $this->baseUrl(); ?>images/zend_framework_logo.png" alt="Zend Framework" width="120" height="60" />
    </a>
</div>
