<div>
    <a href="http://code.google.com/p/gonium">
		Gonium Project
        <!-- <img title="Roxyton Project" src="<?php echo $this->baseUrl(); ?>images/roxyton_project_120x60.png" alt="Roxyton Project" width="120" height="60" /> -->
    </a>
</div>
<div>
	<!-- <a href="<?php echo $this->baseUrl(); ?>docs/">
	   <img title="Roxyton API" src="<?php echo $this->baseUrl(); ?>images/roxyton_api_120x60.png" alt="Roxyton API" width="120" height="60" />
	</a> -->
</div>
<div>	
	<!-- <a href="<?php echo $this->baseUrl(); ?>wblog/">
       <img title="Roxyton Blog" src="<?php echo $this->baseUrl(); ?>images/roxyton_blog_120x60.png" alt="Roxyton API" width="120" height="60" />
    </a> -->
</div>
<div>
    <a href="http://twitter.com/GoniumProject">
		Gonium Twitter
       <!-- <img title="Roxyton Twitter" src="<?php echo $this->baseUrl(); ?>images/roxyton_twitter_120x60.png" alt="Zend Framework" width="120" height="60" />
	   -->
    </a>
</div>
<br />
<div>
    <a href="http://framework.zend.com/">
       <img title="Zend Framework" src="<?php echo $this->baseUrl(); ?>images/zend_framework_logo.png" alt="Zend Framework" width="120" height="60" />
    </a>
</div>
