<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php
echo $this->headTitle();
?>

<?php
echo $this->headMeta();
?>

<link rel="shorcut icon"
	href="<?php
echo $this->baseUrl();
?>../images/favicon.ico" />
<link rel="stylesheet" type="text/css"
	href="<?php
echo $this->baseUrl();
?>../themes/default/css/main.css" />

<?php
echo $this->headLink();
?>

<?php
echo $this->headScript();
?>

<?php
echo $this->headStyle();
?>

</head>
<body>
<div id="global">
<div class="shadow-top-left">
<div class="shadow-top-right">
<div class="shadow-bottom-left">
<div class="shadow-bottom-right">
<div class="shadow-vertical">
<div class="shadow-top"></div>
<div class="shadow-left">
<div class="shadow-right">
<div class="innerbox">
<div class="error">
<div class="error-message"><?php
echo $this->errorMessage;
?></div>
                    <?php
                    if ($this->errorLog)
                    :
                        ?>
                    <div class="error-log"><?php
                        echo $this->errorLog;
                        ?></div>
                    
                    <?php endif;
                    ?>
                </div>
</div>
<!--/innerbox--></div>
<!--/shadow-right--></div>
<!--/shadow-left-->
<div class="shadow-bottom"></div>
</div>
<!--/shadow-vertical--></div>
<!--/shadow-bottom-right--></div>
<!--/shadow-bottom-left--></div>
<!--/shadow-top-right--></div>
<!--/shadow-top-left--></div>
<!--/global-->
</body>
</html>