<p><a href="http://validator.w3.org/check?uri=referer"> <img
	style="width: 88px; height: 31px"
	src="http://www.w3.org/Icons/valid-xhtml10"
	alt="Valid XHTML 1.0 Strict" /> </a> <a
	href="http://jigsaw.w3.org/css-validator/check/referer"> <img
	style="width: 88px; height: 31px"
	src="http://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS!" />
</a> <a
	href="http://jigsaw.w3.org/css-validator/check/referer/?profile=css3">
<img style="border: 0; width: 88px; height: 31px"
	src="http://jigsaw.w3.org/css-validator/images/vcss-blue"
	alt="Valido! CSS 3.0" /> </a></p>
