<div class='dbInfo'>
    <?php
    printf(
    $this->translate('%1$d queries in %2$f seconds', $this->db_queryCount, 
    $this->db_totalTime ? $this->db_totalTime : ''));
    ?>

    <?php
    if ($this->db_AverageQueryLength && $this->db_QueriesPerSecond)
    :
        ?>
      <br />
    <?php
        printf(
        $this->translate('AverageQueryLenght: %1$f | QueriesPerSecond %2$f', 
        $this->db_AverageQueryLength, $this->db_QueriesPerSecond));
        ?>
    
    <?php endif;
    ?>

    <?php
    if ($this->db_longestTime)
    :
        ?>
      <br />
    <?php
        printf(
        $this->translate('Query longestTime: %1$f seconds', 
        $this->db_longestTime));
        ?>
    
    <?php endif;
    ?>

    <?php
    if ($this->db_longestQuery)
    :
        ?>
    
	<div class="code"><?php
        printf(
        $this->translate('longestQuery: %1$s', $this->db_longestQuery));
        ?></div>
    
    <?php endif;
    ?>
</div>